//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossManager_WPF_GUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D[0-9]")]
        public string scannerInputRegex {
            get {
                return ((string)(this["scannerInputRegex"]));
            }
            set {
                this["scannerInputRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int scannerIntIdx {
            get {
                return ((int)(this["scannerIntIdx"]));
            }
            set {
                this["scannerIntIdx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("105,105,105,53,159")]
        public string diplomas_x {
            get {
                return ((string)(this["diplomas_x"]));
            }
            set {
                this["diplomas_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("265,170,130,50,50")]
        public string diplomas_y {
            get {
                return ((string)(this["diplomas_y"]));
            }
            set {
                this["diplomas_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Janez Novak")]
        public string diplomas_mentor {
            get {
                return ((string)(this["diplomas_mentor"]));
            }
            set {
                this["diplomas_mentor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ljubljana")]
        public string diplomas_kraj {
            get {
                return ((string)(this["diplomas_kraj"]));
            }
            set {
                this["diplomas_kraj"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Za doseženo {0}. mesto\r\nna šolskem tekmovanju iz krosa.")]
        public string diplomas_besedilo {
            get {
                return ((string)(this["diplomas_besedilo"]));
            }
            set {
                this["diplomas_besedilo"] = value;
            }
        }
    }
}
